# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.15.202201'

RELEASE_GIT_HEAD = '8fbe0c62160287e36bbf732f4140378ee2fa9275'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sonar98/yt-dlp'

ORIGIN = 'sonar98/yt-dlp'

_pkg_version = '2024.10.15.202201'
